FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/utils/forms.py
from FlaskBlueprintTemplateFrontend.utils.extensions import(
    FlaskForm,
    StringField,
    PasswordField,
    SubmitField,
    DataRequired,
    ValidationError,
    Email,
    EqualTo,
    Length,
    re,
    IPAddress
)
from wtforms import BooleanField


class ProjectForm(FlaskForm):
    """
    Form for setting Unreal Engine paths: Unreal launcher, project, and scripts paths.
    """
    PROJECT_NAME = StringField('Project name', validators=[DataRequired()])
    EXCLUDED = BooleanField('Exclude project')


    submit = SubmitField(label="Insert project")

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/__init__.py
"""
Service Main Application.
Describe here what your service is doing.

This file contains both function to initialized Flask and Celery App.
You shouldn't have to change those functions except for advance functionality.

"""
from FlaskBlueprintTemplateFrontend.utils.extensions import Flask
from FlaskBlueprintTemplateFrontend.routes import routes_bp

def create_app(config_filename=None, testing=False):
    """
    Create and configure the Flask application.

    Parameters:
    - config_filename (str): The configuration file to load.
    If None,  defaults to 'config/settings-dev.py'.

    Returns:
    - app (Flask): The configured Flask application instance.
    """
    #: Instanciate a Flask App with the name of the service
    app = Flask(__name__)

    #: Load Flask Configuration
    #:
    #: By Default the application will load `config/settings.py`.
    #: For testing or dev purposes, you can pass a python configuration
    #: file path as parameter of this function.
    if config_filename:
        app.config.from_pyfile(config_filename)
    else:
        app.config.from_pyfile('config/settings-dev.py')

    #: Testing mode
    #:
    #: Flask changes some internal behavior so it's easier to test, and other
    #: extensions can also use the flag to make testing them easier.
    if testing is True:
        app.config["TESTING"] = True

    # Register routes

    from  FlaskBlueprintTemplateFrontend.routes import register_routes
    register_routes(app)

    return app

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/config/__init__.py
"""Config Init Module."""

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/routes.py
"""
Frontend 1.0 Example - Routes/Views.

This is a placeholder/example of routes/views for our api blueprint.
All our Views comes here or could be seperated into several files

"""
from FlaskBlueprintTemplateFrontend.utils.extensions import (
    Blueprint,
    render_template
)

routes_bp = Blueprint('routes_1_0', __name__)

@routes_bp.route('/home')
def home():
    """
    Renders the home page.

    Returns:
        Response: Rendered 'index.html' template.
    """
    return render_template('index.html')

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/routes/__init__.py
from .routes import routes_bp  # Import the blueprint

def register_routes(app):
    """Registers all routes with the Flask app."""
    app.register_blueprint(routes_bp)

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/routes/routes.py
"""
Frontend 1.0 Example - Routes/Views.

This is a placeholder/example of routes/views for our api blueprint.
All our Views comes here or could be seperated into several files

"""
from FlaskBlueprintTemplateFrontend.utils import forms
from FlaskBlueprintTemplateFrontend.utils.utils import *
from FlaskBlueprintTemplateFrontend.utils.extensions import (
    Blueprint,
    render_template
)

routes_bp = Blueprint('routes', __name__)

@routes_bp.route('/')
def home():
    """
    Renders the home page.

    Returns:
        Response: Rendered 'index.html' template.
    """
    return render_template('index.html')


@routes_bp.route("/get_projects", methods=['GET'])
def get_projects():
    return send_request('get_projects', "GET", {})


@routes_bp.route("/insert_project", methods=["GET", "POST"])
def insert_project():
    form = forms.ProjectForm()

    if request.method == "GET":
        return render_template("projects_form.html", form=form)
    elif request.method == "POST":
        if form.validate_on_submit():
            params = {
                "project_name" : form.PROJECT_NAME.data,
                "excluded" : form.EXCLUDED.data
            }
        return_value = send_request("ins_projects", "POST", params)
        return return_value

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/routes/versions/routes_1_0/routes.py
"""
Frontend 1.0 Example - Routes/Views.

This is a placeholder/example of routes/views for our api blueprint.
All our Views comes here or could be seperated into several files

"""
from FlaskBlueprintTemplateFrontend.utils.extensions import (
    Blueprint,
    render_template
)

from FlaskBlueprintTemplateFrontend.routes.versions.routes_1_0 import routes_bp

@routes_bp.route('/home')
def home():
    """
    Renders the home page.

    Returns:
        Response: Rendered 'index.html' template.
    """
    return render_template('index.html')

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://unpkg.com/feather-icons"></script>
</head>
<body>
    <div class="container">
        {% include 'nav_bar.html' %}
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="flash {{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/flash.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        feather.replace();
    </script>
</body>
</html>

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}

    <section class="hero text-center py-5">
        <h1>Index Template </h1>
    </section>

{% endblock %}

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/templates/nav_bar.html
<header>
    <nav>
        <a href="/"><i data-feather="home"></i> Home</a>
        <a href="/get_projects"> Get projects</a>
        <a href="/insert_project"> Create projects</a>
    </nav>
</header>

FlaskBlueprintTemplateFrontend/FlaskBlueprintTemplateFrontend/templates/projects_form.html
{% extends "base.html" %}

{% block title %}Projects page{% endblock %}
{% block content %}
<div class="container mt-5">
    <form method="POST" action="{{ url_for('routes.insert_project') }}" >
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="mb-3">
                {{ form.PROJECT_NAME.label(class="form-label") }}
                {{ form.PROJECT_NAME(class="form-control {% if form.PROJECT_NAME.errors %}is-invalid{% endif %}") }}
                {% for error in form.PROJECT_NAME.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>
            <!-- Checkbox -->
            <div class="mb-3 form-check">
                {{ form.EXCLUDED(class="form-check-input", type="checkbox") }}
                {{ form.EXCLUDED.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="d-grid">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}